# Generated by Django 4.2.7 on 2023-12-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='brandname', max_length=100)),
                ('logo', models.ImageField(null=True, upload_to='photos/product')),
                ('slug', models.SlugField(blank=True, default='brandname', null=True)),
                ('soft_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
