# Generated by Django 4.2.7 on 2023-12-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, default='brandname', null=True),
        ),
    ]
