# Generated by Django 4.2.7 on 2023-12-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
