# Generated by Django 4.2.7 on 2023-11-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_check_max_price_gt_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='check_max_price_gt_price',
        ),
    ]
