# Generated by Django 4.2.7 on 2023-12-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='end_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='is_offer_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='minimum_amount',
            field=models.IntegerField(default=100),
        ),
    ]
