# Generated by Django 4.2.7 on 2023-12-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_discount_category_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
