# Generated by Django 4.2.7 on 2023-12-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='end_date',
            field=models.DateField(default=1, verbose_name='11-11-1111'),
            preserve_default=False,
        ),
    ]
