# Generated by Django 4.2.7 on 2023-12-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_category_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='end_date',
            field=models.DateField(default='1111-11-11', null=True),
        ),
    ]
