# Generated by Django 4.2.7 on 2023-11-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_coupon_coupon_redeemed_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='maximum_amount',
            field=models.IntegerField(default=1000),
        ),
    ]
