# Generated by Django 4.2.7 on 2023-11-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_coupon_maximum_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(default='Damaged Product', max_length=150),
        ),
    ]
